language: python
env:
  - RASTERIO_VERSION=0.26.0
python:
  - "2.7"
  - "3.4"
cache:
  directories:
    - $HOME/.pip-cache/
    - $HOME/wheelhouse
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdal1h gdal-bin
  - curl -L https://github.com/mapbox/rasterio/releases/download/$RASTERIO_VERSION/rasterio-travis-wheels-$TRAVIS_PYTHON_VERSION.tar.gz > /tmp/wheelhouse.tar.gz
  - tar -xzvf /tmp/wheelhouse.tar.gz -C $HOME
install:
  - "pip install -U pip"
  - "pip install --use-wheel --find-links=$HOME/wheelhouse -e .[test] --cache-dir $HOME/.pip-cache"
script:
  - py.test --cov rio_color --cov-report term-missing
after_success:
  - coveralls
